### ISSUE TITLE
Not support laravel ^6

### ISSUE THREAD

**Issue by harlamoff** [jarektkaczyk/eloquence-mappable#8]

**Comment by jannejava** [comment]
First, thanks for a great package!

Is the update in requirements in composer.js the only thing that's needed to make Mappable Laravel 6 compatible? Like this pull request:

https://github.com/jarektkaczyk/eloquence-mappable/pull/6

**Comment by Gemius01** [comment]
Please fix that :(,  is the only package that i need to update

**Comment by breaktag** [comment]
Please merge this PR. This is stopping me from upgrading from Laravel 5.8 to 6.*
